### ISSUE TITLE
import module failed with exception

### ISSUE THREAD

**Issue by Dierk** [IntelliJ-Frege/intellij-frege#69]
stack trace
```
java.lang.IllegalStateException: Cannot create an element class com.intellij.psi.PsiElement
	at com.plugin.frege.psi.FregeElementFactory.createVirtualEndDecl(FregeElementFactory.kt:257)
	at com.plugin.frege.inspections.ImportAdder.addImport(FregeAddImportQuickFix.kt:104)
	at com.plugin.frege.inspections.FregeAddImportQuickFix$showPromptToPickCandidate$1$1.invoke$lambda-0(FregeAddImportQuickFix.kt:60)
```
when trying to quick fix
```
module Startme where

main = do
    greeting "Dierk"
	
```
where greeting is defined in Dependent.fr in the same folder/package (source root)
```
module Dependent where

greeting name = "Hello, " ++ name
```

**Comment by kkarnauk** [comment]
Thanks! We forgot to test 'add import' after lexer changes. Now it works.
